name: lumiframe
description: "A bleeding-edge digital photo frame app with dynamic theming, cloud integration, and advanced slideshow features."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  photo_manager: ^3.0.0  # For local media access
  image_picker: ^1.0.7   # For picking photos (used in MediaService)
  video_player: ^2.9.1   # For video playback in slideshow
  cached_network_image: ^3.3.1  # For image caching
  flutter:
    sdk: flutter

  # State Management & Routing
  get: ^4.6.6
  # Firebase Integration (Auth, Firestore, Storage)
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.2.1  # For cloud media upload/sync

  # Media Handling
  # image_picker: ^1.1.2  # Local/camera/gallery access

  # UI/UX Enhancements
  google_fonts: ^6.2.1  # Dynamic fonts
  flex_color_picker: ^3.5.0  # Custom color selection
  flutter_feather_icons: ^2.0.0+1  # Icons
  intl: ^0.19.0  # Date/time formatting
  timezone: ^0.9.4  # Timezone for time-based themes

  # Casting & External Displays
  flutter_cast_video: ^1.0.0  # Chromecast/AirPlay support (may need platform-specific setup)

  # Storage & Persistence
  get_storage: ^2.1.1  # Local storage for settings

  # Utilities
  url_launcher: ^6.3.0  # Email/support links

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting & Analysis
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Assets (add your images/fonts here if needed)
  assets:
    - assets/images/  # Example: for logos/backgrounds

  # Fonts (if not using google_fonts exclusively)
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf