name: lumiframe
description: "A bleeding-edge digital photo frame app with dynamic theming, cloud integration, and advanced slideshow features."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management & Routing
  get: ^4.6.6

  # Firebase Integration (Auth, Firestore, Storage)
  firebase_core: ^3.6.0
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  firebase_storage: ^12.3.0  # For cloud media upload/sync

# Login methods
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1
  flutter_facebook_auth: ^7.1.1

# Media Handling & Display
  photo_manager: ^3.0.0  # For local media access
  image_picker: ^1.1.2   # For picking photos (used in MediaService)
  video_player: ^2.9.1   # For video playback in slideshow
  cached_network_image: ^3.3.1  # For image caching

  # UI/UX Enhancements
  google_fonts: ^6.2.1  # Dynamic fonts
  flex_color_picker: ^3.5.0  # Custom color selection
  flutter_feather_icons: ^2.0.0+1  # Icons
  intl: ^0.19.0  # Date/time formatting
  timezone: ^0.9.4  # Timezone for time-based themes

  # Casting & External Displays
  flutter_cast_video: ^1.0.0  # Chromecast/AirPlay support (may need platform-specific setup)

  # Storage & Persistence
  get_storage: ^2.1.1  # Local storage for settings

  # Utilities
  url_launcher: ^6.3.0  # Email/support links
  local_auth: ^2.3.0  # Biometric authentication
  package_info_plus: ^8.0.0  # App version info
  video_thumbnail: ^0.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting & Analysis
  flutter_lints: ^6.0.0
  
  # App Icon Generation
  flutter_launcher_icons: ^0.14.1

# Flutter Launcher Icons Configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true  # Required for App Store submission
  
  # Adaptive icon for Android (API 26+)
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"
  
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#FFFFFF"
    theme_color: "#2196F3"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  # Assets (add your images/fonts here if needed)
  assets:
    - assets/images/  # Example: for logos/backgrounds

  # Fonts (if not using google_fonts exclusively)
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf